### ISSUE TITLE
Github Action errors out

### ISSUE THREAD

**Issue by ch264** [ocular-d/md-linkcheck-action#9]
**Describe the bug**
I get the following error message when the github action runs: Docker build failed with exit code 1, back off 6.241 seconds before retry.

**To Reproduce**
Follow instructions on how to implement github action.

**Expected behavior**

**Screenshots**

Here is my code  in the .github/workflows/linkcheck.yml
```on:
  pull_request:
    branches:
    - master
name: Testing linkcheck
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: md-linkcheck
      uses: ocular-d/md-linkcheck-action@1.0.1```

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]
 - Version [Version 78.0.3904.108]

**Additional context**
none

**Comment by ocular-d** [comment]
Thank you for opening an issue!

Yes, that is because the repositories of Alpine Linux changed, because of that the image is not building anymore.

We will release a new version which is adjusted to these asap sometime this week.

Thanks again for reporting!

**Comment by ch264** [comment]
@ocular-d Thanks, I tried it again and now it runs. I am closing this issue.
